# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7430c13170395516e09d7aa9250afa8023a17b5c9d18b638fb152e9c839724077d82e3511bdfd9e4b61299e0cc18a875df156a47da055924254ed82cc4895f16

test:
  secret_key_base: e28abcfbbc2abc884a2c8b4de34ee6ab1f36daf2591257b26d5291888544ef5328df67a92504e34babcda65b0dab6c73a080dad0cfb92cefabe2e48652c2387d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
